spring:
  redis:
    host: 132.121.80.55
    port: 31486
    password: 95a9b4b048dc008aaff16b6f83adb5e1
    database: 4
    timeout: 600000 # 600秒
    lettuce:
      pool:
        max-active: 200
        max-wait: 30000 # 30秒
        min-idle: 10
        max-idle: 100

gateway:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: postgres
    username: postgres
    password: 123123
