spring:
  redis:
    host: 132.121.80.55
    port: 65517
    password: hd_smartant#Ki!L2xop
    database: 4
    timeout: 600000 # 600秒
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 30000 # 30秒
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池中的最大空闲连接
        max-idle: 100

gateway:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: 132.108.229.34
    port: 5434
    database: szgiswebsg
    username: V-JINGH
    password: Jh_160203.